# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
      name: Check out code
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
      name: Install dependencies
    - run: yarn build
      name: Build extension
    - run: yarn lint
      name: Lint code
    - run: yarn test:ci
      name: Run tests
    - run: yarn package
      name: Package extension
    - uses: actions/upload-artifact@v2
      name: Upload artifacts
      with:
        name: bclub-tools
        path: dist/bclub-tools
